services:
  app:
    image: node:20-alpine
    command: sh -c "npm install && npm start"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - CHOKIDAR_USEPOLLING="true"
      - WATCHPACK_POLLING=true 